name: CD PIPELINE 
on:
  workflow_dispatch:
    inputs:
      target_job:
        description: 'Sélectionnez le job CD à exécuter'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - burnout

defaults:
  run:
    working-directory: ./chatbot

jobs:
  burnout:
    if: github.event.inputs.target_job == 'burnout' || github.event.inputs.target_job == 'all'
    runs-on: self-hosted
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container 
      - name: Checkout Code
        uses: actions/checkout@v4
        # Test de validation Green-DevOps
      - name: Docker Burn Test
        run: |
          docker run --rm python:3.9-slim python3 -c "
          import time
          start = time.time()
          while time.time() - start < 30: # Brûle du CPU pendant 30s
            [x**2 for x in range(5000)]
          "
