name: CI PIPELINE

on:
  workflow_dispatch:
    inputs:
      target_job:
        description: 'Sélectionnez le job à tester'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - setup
          - install
          - lint
          - test
          - build
          - build-artifact
          - docker-build
          - docker-push

defaults:
  run:
    working-directory: ./chatbot

jobs:
# 1. SETUP - Préparation de l'environnement
  setup:
    if: github.event.inputs.target_job == 'setup' || github.event.inputs.target_job == 'all'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python3 --version

# 2. INSTALL - Dépendances
  install:
    needs: [setup]
    if: always() && (github.event.inputs.target_job == 'install' || github.event.inputs.target_job == 'all')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt ruff pytest --break-system-packages

# 3. LINT - Vérification de syntaxe 
  lint:
    needs: [install]
    if: always() && (github.event.inputs.target_job == 'lint' || github.event.inputs.target_job == 'all')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: /home/medyassine/.local/bin/ruff check .

# 4. TEST - Vérification 
  test:
    needs: [lint]
    if: always() && (github.event.inputs.target_job == 'test' || github.event.inputs.target_job == 'all')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests/ || true

# 5. BUILD - Compilation
  build:
    needs: [test]
    if: always() && (github.event.inputs.target_job == 'build' || github.event.inputs.target_job == 'all')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m compileall app/

# 6. BUILD-ARTIFACT - Packaging
  build-artifact:
    needs: [build]
    if: always() && (github.event.inputs.target_job == 'build-artifact' || github.event.inputs.target_job == 'all')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Create Deployment Package
        run: |
          mkdir -p dist
          tar -czvf dist/chatbot-artifact.tar.gz .
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatbot-package
          path: chatbot/dist/chatbot-artifact.tar.gz
          retention-days: 1

# 7. DOCKER-BUILD - Création de l'image
  docker-build:
    needs: [build-artifact]
    if: always() && (github.event.inputs.target_job == 'docker-build' || github.event.inputs.target_job == 'all')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-bot:latest .

# 8. DOCKER-PUSH - Envoi
  docker-push:
    needs: [docker-build]
    if: always() && (github.event.inputs.target_job == 'docker-push' || github.event.inputs.target_job == 'all')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-bot:latest
