name: Calculator Service CI/CD - Energy Optimized
permissions:
  contents: read
  actions: read  

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./calculator-python
        

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize Eco-CI
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: start-measurement
          geo-location: fr
          env:
          CO2_SIGNAL_API_KEY: ${{ secrets.CO2_SIGNAL_API_KEY }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      #- name: Stress Test
        #run: |
         # chmod +x ../../stress-tests/stress_workload.sh
         # bash ../../stress-tests/stress_workload.sh

     # - name: Get Stress Metrics
     #   uses: green-coding-solutions/eco-ci-energy-estimation@v4
     #   with:
      #    task: get-measurement
       #   label: 'Stress-Test-4-Cores'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt ruff pytest

      - name: Get Installation Metrics
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'Installation'

      

      - name: Build (Compile Bytecode)
        run: python -m compileall app/
          
      - name: Get Build Metrics
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'Compile Bytecode'

      - name: Static Code Analysis (Ruff)
        run: ruff check .

      - name: Get Linting Metrics
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'Linter (Ruff)'

      - name: Unit Tests (Pytest)
        run: pytest tests/

      - name: Get Test Metrics
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'Tests (Pytest)'

      - name: Finalize & Display Results
        if: always()
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results
          send-data: true
          branch-name: ${{ github.ref_name }}
          export-json: true

      - name: Check if file exists (Debug)
        run: |
          echo "Recherche du fichier dans tout le dossier du runner..."
          find . -name "energy-export.json"

      - name: Upload Energy Report
        uses: actions/upload-artifact@v4
        with:
          name: energy-report-${{ github.run_id }}
          path: |
            **/energy-export.json
            ./energy-export.json
          if-no-files-found: warn
